# Generated by Django 3.2.4 on 2021-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0002_auto_20210630_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('total_donations', models.IntegerField(blank=True, default=0, null=True)),
                ('total_loans', models.IntegerField(blank=True, default=0, null=True)),
                ('current_balance', models.IntegerField(blank=True, default=0, null=True)),
                ('outstanding_loans', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='remaining_loan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_donated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='total_loan',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
