# Generated by Django 3.2.6 on 2021-09-06 10:02

import autoslug.fields
from django.db import migrations

from ..models import QarzUser


def migrate_data_forward(apps, schema_editor):
    for instance in QarzUser.objects.all():
        print("Generating slug for {0}".format(instance))
        instance.save()  # This Will trigger slug updates


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0003_auto_20210630_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarzuser',
            name='unique_id',
            field=autoslug.fields.AutoSlugField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(
            migrate_data_forward,
            migrate_data_backward,
        ),
    ]
